server:
  port: 10001
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  host:
    connect-timeout-millis: 15000 #HTTP连接超时需要比Hystrix的大
    socket-timeout-millis: 60000 #socket超时
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    meal-service: /meal/**
    order-service: /order/**
    user-service: /user/**
    upload-service: /**
    auth-service: /auth/**
  add-host-header: true #携带hosy本身的请求头信息
  sensitive-headers: #敏感头设置为null
ribbon:
  ConnectTimeout: 10000 # 连接超时时间(ms)
  ReadTimeout: 10000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms

mk:
  jwt:
    pubKeyPath: C:/tmp/rsa/rsa.pub # 公钥地址
    cookieName: MK_TOKEN

  filter:
    allowPaths:
      - /api/user/userguest/validuser #验证用户
      - /api/auth #鉴权